version: "3.9"
services:
  # frontend:
  #   build:
  #     context: frontend/
  #   ports:
  #     - 3000:80
  backend:
    build:
      context: java/
    ports:
      - 8088:8088
  cqf-ruler-a:
    image: alphora/cqf-ruler
    ports:
      - 8080:8080
  cqf-ruler-b:
    image: alphora/cqf-ruler
    ports:
      - 8082:8080
